### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ghost** [cameronmaske/django-boilerplate-dotcloud#1]
here what i have
http://krovostokru-almapool.dotcloud.com/
no design
no admin
http://krovostokru-almapool.dotcloud.com/admin/
how to come back to normal django interface?

**Comment by cameronmaske** [comment]
Looking at the site, it appears your django project files have not yet been pushed to DotCloud. 
Have you committed and dotcloud push 'project_name' successfully?

Note: This repo is still in an alpha state.

**Comment by ghost** [comment]
here is what i did

$ mkdir krovostokru  
$ cd krovostokru
$ virtualenv --python=python2.6 dev-env (# i have python 2.6)
$ source dev-env/bin/activate 
$ pip install django
$ django-admin.py startproject --template https://github.com/cameronmaske/django-boilerplate-dotcloud/zipball/master krovostokru
$ cd krovostokru 
$ python install.py krovostokru 
then:
$ dotcloud create krovostokru
$ dotcloud pucsh krovostokru .
$ dotcloud pucsh krovostokru . ( 2 times )

**Comment by cameronmaske** [comment]
What was the output from DotCloud when you tried to push?

**Comment by ghost** [comment]
12:23:34 [www] -- Build failed: "pip install --download-cache=~/.pip-cache -r requirements.txt" failed with return code 1
12:23:35 ---> Aborting due to some build failure

Deployment finished. Your application is available at the following URLs
www: http://krovostokru-almapool.dotcloud.com/
(dev-env)bash-4.2$

**Comment by cameronmaske** [comment]
Ok, while in the main directory (where requirements.txt is) and the virtual-env activated can you re-freeze the requirements.txt with 
pip freeze > requirements.txt
And try the push again.

**Comment by ghost** [comment]
(dev-env)bash-4.2$ pip freeze > requirements.txt
(dev-env)bash-4.2$ dotcloud push krovostokru .
(dev-env)bash-4.2$ dotcloud push krovostokru .
the same on http://krovostokru-almapool.dotcloud.com/
maybe i should add some django app?

**Comment by cameronmaske** [comment]
I'm having trouble replicating the bug. There should be a default index page. 
Have you tried running the server locally (manage.py runserver). Does that works ok?
Can you give me the full print out from when you try to DotCloud push?

**Comment by ghost** [comment]
http://dl.dropbox.com/u/2153133/dotcloud_push_log.txt

bash-4.2$ python manage.py runserver
Error: Could not import settings 'config.environments.development' (Is it on sys.path?): No module named path
bash-4.2$

**Comment by cameronmaske** [comment]
Hmm, it appears that your not in your virtual environment for the development. I've this project on my end, and found a bug in the wsgi.py, but it doesn't appear like that would cause the issue, I still had a successful development to DotCloud. 

From the log it looks like something went wrong with the database and south's tagging. 

I would try destroying the app on DotCloud and try recreating and deploying it.

**Comment by ghost** [comment]
aha thanks i tried reinstalling -- http://127.0.0.1:8000 -- working
