### ISSUE TITLE
apps

### ISSUE THREAD

**Issue by ghost** [cameronmaske/django-boilerplate-dotcloud#2]
HI! how to add apps?

i uploaded new app ( 'photo' from this tut http://lightbird.net/dbe/photo4.html ) to apps and added 'photo' to INSTALLED_APPS
but it does not find setting from there

```
File "/home/illucent/1amedia/12JULY2012/projectname/krovostokru/krovostokru/apps/photo/models.py", line 3, in <module>
from settings import MEDIA_ROOT
ImportError: No module named settings
```

**Comment by cameronmaske** [comment]
Hi, 
I'm sorry, but I'm not sure I can help with this. Do you have experience with Django, or are you new to it? 
If you are new, I can recommend a few resources to get started... 
- http://www.djangobook.com/
- http://python.mirocommunity.org/video/1617/pycon-2010-introduction-to-dja
- http://gettingstartedwithdjango.com/resources/gigantuan.html
- http://godjango.com/
